[package]
name = "enoew/plumber-portal"
version = "0.1.0"
description = "Plumber management portal"

[dependencies]
"wasmer/python" = "3.11"

[fs]
"/app" = "."

[[command]]
name = "server"
module = "wasmer/python:python"
runner = "https://webc.org/runner/wcgi"

[command.annotations.wcgi]
script = "app:app"
